const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const os = require("node:os");
const crypto = require("node:crypto");
const { spawnSync } = require("node:child_process");
const { Queue } = require("../src/queue");
const { ModelGuard } = require("../src/model-guard");
const { AlertStore, monitorFile } = require("../src/monitoring");
test("encrypted recording backup restores accepted queue jobs and their input files", t => {
  if (spawnSync("age-keygen", ["--version"]).status !== 0) return t.skip("age tools are required for encrypted backup verification");
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "englisheval-backup-test-"));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const recordings = path.join(root, "recordings");
  fs.mkdirSync(path.join(recordings, "pending"), { recursive: true });
  const file = path.join(recordings, "pending", "fixture"); fs.writeFileSync(file, "synthetic input");
  const queue = new Queue(path.join(recordings, "queue.sqlite"), { health: () => null });
  const admission = queue.enter("synthetic-owner"); const { grant } = queue.grant("synthetic-owner"); queue.beginUpload("synthetic-owner", grant);
  const id = crypto.randomUUID(); queue.accept(id, "synthetic-owner", admission.id, { inputPath: file, record: { id } });
  const models = new ModelGuard(queue);
  const request = models.acquire("question", 4000, 45000);
  models.finish(request.id, { status: 429, retryMs: 90000 });
  queue.close();
  const identity = path.join(root, "test-identity");
  assert.equal(spawnSync("age-keygen", ["-o", identity]).status, 0);
  const recipient = spawnSync("age-keygen", ["-y", identity], { encoding: "utf8" }).stdout.trim();
  const backups = path.join(root, "backups");
  const monitor = new AlertStore(monitorFile(recordings));
  monitor.set("heartbeat", 12345);
  monitor.db.prepare("INSERT INTO events(id,key,created,level,body,status,receipt) VALUES(?,?,?,?,?,?,?)").run("synthetic-event", "memory", 12345, 2, "synthetic alert", "sent", JSON.stringify({ openDingId: "synthetic-ding" }));
  const backup = spawnSync("bash", [path.join(__dirname, "../scripts/backup-recordings.sh")], { env: { ...process.env, RECORDINGS_DIR: recordings, BACKUP_DIR: backups, BACKUP_AGE_RECIPIENT: recipient } });
  assert.equal(backup.status, 0, `Encrypted synthetic backup failed: ${backup.stderr.toString()}`);
  monitor.set("heartbeat", 67890);
  monitor.close();
  const archive = path.join(backups, fs.readdirSync(backups).find(file => file.endsWith(".age")));
  const restore = path.join(root, "restored"); fs.mkdirSync(restore);
  assert.equal(spawnSync("bash", [path.join(__dirname, "../scripts/restore-recordings-backup.sh"), archive, identity, restore]).status, 0);
  const restoredMonitor = new AlertStore(monitorFile(path.join(restore, "recordings")));
  assert.equal(restoredMonitor.get("heartbeat"), 12345);
  assert.equal(restoredMonitor.db.prepare("SELECT status FROM events").get().status, "sent");
  restoredMonitor.close();
  const restored = new Queue(path.join(restore, "recordings", "queue.sqlite"), { health: () => null });
  assert.equal(restored.status(id, "synthetic-owner").state, "queued");
  assert.equal(restored.claim().id, id);
  const restoredModels = new ModelGuard(restored);
  assert.equal(restoredModels.acquire("question", 4000, 45000).reason, "circuit");
  assert.equal(restoredModels.metrics().find(item => item.scope === "question").tokens, 4000);
  restored.close();
  assert.equal(fs.readFileSync(path.join(restore, "recordings", "pending", "fixture"), "utf8"), "synthetic input");
});
